- documentation/docs/requirements/use-case-descriptions.md
Patrick: added some user stories and use cases. Formatted sections as well.
Kroos: added diagram from canvas requirements
> Use case descriptions

- documentation/docs/system-architecture/component-descriptions.md
> component descriptions

- documentation/docs/development-plan/version-control.md
Wrote and edited the version control doc, ready to be reviewed.
> Version control

- .github/workflows/node.js.yml
> CI/CD Test

- src/test/extension.test.ts
fixed unit test by placing it under one 'describe'
> fixed getsSettings test

- src/test/extension.test.ts
> Wrote Unite Test

- src/test/extension.test.ts
Overwritten by accident test so I added it back.
> Added test back

- src/test/extension.test.ts
Wrote integration tests for each use case(7 total). Tried to follow a similar format for each for ease of understanding. Comments to signify where integration testing starts and what test responds to what use case. Some tests will need to have more added but the features described in some of the use cases are not fully complete so it is hard to test for that.
Based all the work here off of info from within the 'extension.ts' file, as it explains the search function and the command parameters that are needed. These commands reflect the options users have when using the vscode extension.
> Integration tests sprint3

- media/main.js
- package-lock.json
- package.json
- src/extension.ts
Reverts Capstone-Projects-2023-Fall/project-code-review-chatbot#63
> Revert "Code review josh - convert output to a list of dropdowns"

- src/commitIntervention/pre-commit
added more script so the user can confirm the commit after reviewing the feedback.
now upon commit, there should be a popup that confirms with the user.
> bash update

- package.json
- src/extension.ts
commit hook detection; If the extension can not find a pre-commit hook it will prompt user about it, and upon approval it will automatically apply the pre-commit hook
> automate pre-commit hook

- media/main.js
- package.json
- src/extension.ts
added a button on the bottom of the extension screen to learn more about the previous response
the layout itself is not pretty and experimental but the functionality seem to work.
> added a button on the bottom of the extension screen to learn more about the previous response

- documentation/docs/testing/integration-testing.md
- documentation/docs/testing/unit-testing.md
Wrote documentation for testing on the docusaurus page. All existing Unit tests for front and back end along with integration tests are covered as of **11/5/23**. Any newly added tests will need to be appended to the page.
The information I chose to include and format choices were done to model "study buddy" & "sokroban" which are projects from previous semesters that are displayed on canvas/ian's capstone website.
> Testing documentation

- src/extension.ts
- if there are no pre-commit hooks enabled on users .git/hooks, by enabling it adds the hook
- if user goes into the settings and disables the feature, the hook gets disabled and the pre-commit check will not run.
> added functionality to disable automatic code review upon commit

- src/commitIntervention/pre-commit
- src/extension.ts
- if the user commits through the terminal, It will now ask the user in the terminal rather than prompting a popup
- if the user commits through the GUI, it will still promp the popup
> Updated Alerting the user on commit

- package.json
- server/code-review-chatbot/resources/views/welcome.blade.php
- server/code-review-chatbot/routes/api.php
Reverts Capstone-Projects-2023-Fall/project-code-review-chatbot#96
> Revert "api experimental change"

- src/commitIntervention/pre-commit
fixed windows pre-commit hook support
> fixed windows pre-commit hook support

- media/main.js
The status of if a checkbox is ticked or not is sent to an array. The status is a string that describes the checkbox title, checkbox id, and text that states if checked or NOT checked. 
How the info is formatted or where it is stored to should be easy to change in the future if something needs to be done for the server to receive info easier.
> Checklist user suggestions brady

- media/main.js
- src/commitIntervention/pre-commit
- modified main.js
- modified pre-commit message
> Minor changes

- server/code-review-chatbot/app/Http/Controllers/AdminController.php
- server/code-review-chatbot/resources/views/navigation-menu.blade.php
- server/code-review-chatbot/resources/views/profile/admin_dashboard.blade.php
- server/code-review-chatbot/routes/web.php
Created the admin panel and web route.
> Admin Panel

- src/extension.ts
- added logging for commands
- git hash logging for commits 
- timestamp timezone change ( UTC -> EST)
> Database logging changes

- server/code-review-chatbot/app/Http/Controllers/AdminController.php
- server/code-review-chatbot/app/Http/Kernel.php
- server/code-review-chatbot/app/Http/Middleware/EnsureIsAdmin.php
- server/code-review-chatbot/app/Models/User.php
- server/code-review-chatbot/database/migrations/2023_12_03_020613_add_is_admin_to_users_table.php
- server/code-review-chatbot/resources/views/admin-dashboard.blade.php
- server/code-review-chatbot/routes/web.php
- added a table in admin dashboard that shows all the current users
- only admins are allowed to get into the admin dashboard
> Admin Dashboard

- server/code-review-chatbot/app/Http/Controllers/AdminController.php
- server/code-review-chatbot/resources/views/admin-dashboard.blade.php
- server/code-review-chatbot/resources/views/log.blade.php
- server/code-review-chatbot/routes/web.php
- added log page in the admin panel
- can search through the logs
> Adminpanel log

- documentation/docs/requirements/use-case-descriptions.md
Rewrote the user case to fit the current state of our project.
> Crc 151 - User case updated

- media/main.js
- package.json
- src/extension.ts
Reverts Capstone-Projects-2023-Fall/project-code-review-chatbot#166
> Revert "fixed learnmore throwing errors"

- media/main.js
- package.json
- src/extension.ts
Reverts Capstone-Projects-2023-Fall/project-code-review-chatbot#167
> Revert "Revert "fixed learnmore throwing errors""

- documentation/docs/requirements/use-case-descriptions.md
- documentation/docs/system-architecture/sequenceDiagrams.md
> All cases of sequence diagram are updated

- documentation/docs/testing/acceptence-testing.md
> Acceptance Test Report
